{"timestamp": "2025-07-28T21:18:49.934299", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 18, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:18:50.040264", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 24, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:21:16.540694", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 18, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:21:16.645184", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 24, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:36:10.749559", "level": "CRITICAL", "message": "Error al iniciar aplicación: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "main", "line": 86, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 52, in main\n    app = create_application()\n          ^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 41, in create_application\n    app.setAttribute(Qt.ApplicationAttribute.AA_EnableHighDpiScaling)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'"}
{"timestamp": "2025-07-28T21:36:51.277567", "level": "CRITICAL", "message": "Error al iniciar aplicación: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "main", "line": 86, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 52, in main\n    app = create_application()\n          ^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 41, in create_application\n    app.setAttribute(Qt.ApplicationAttribute.AA_EnableHighDpiScaling)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'"}
{"timestamp": "2025-07-28T21:39:28.715602", "level": "CRITICAL", "message": "Error al iniciar aplicación: 'LoginWindow' object has no attribute 'login_failed'", "module": "main", "function": "main", "line": 87, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 79, in main\n    login_window.login_failed.connect(on_login_failed)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'LoginWindow' object has no attribute 'login_failed'"}
{"timestamp": "2025-07-28T21:41:59.218639", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 36, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:41:59.300190", "level": "CRITICAL", "message": "Error al iniciar aplicación: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "main", "line": 63, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 38, in main\n    app = create_application()\n          ^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 25, in create_application\n    app.setAttribute(Qt.ApplicationAttribute.AA_EnableHighDpiScaling)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'"}
{"timestamp": "2025-07-28T21:44:41.660047", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 46, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:44:41.711925", "level": "CRITICAL", "message": "Error al iniciar aplicación: cannot access local variable 'Qt' where it is not associated with a value", "module": "main", "function": "main", "line": 73, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 48, in main\n    app = create_application()\n          ^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 27, in create_application\n    app.setAttribute(Qt.AA_EnableHighDpiScaling)\n                     ^^\nUnboundLocalError: cannot access local variable 'Qt' where it is not associated with a value"}
{"timestamp": "2025-07-28T21:46:21.249672", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 39, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:21.273679", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 27, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:21.417480", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 61, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:29.411245", "level": "INFO", "message": "Usuario autenticado: luis", "module": "main", "function": "on_login_success", "line": 52, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:29.427388", "level": "INFO", "message": "Ventana principal creada para luis", "module": "main_window", "function": "__init__", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:29.500895", "level": "INFO", "message": "Ventana principal mostrada", "module": "main", "function": "on_login_success", "line": 56, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:45.625227", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 39, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:45.649195", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 27, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:45.785968", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 61, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:53.704071", "level": "INFO", "message": "Usuario autenticado: luis", "module": "main", "function": "on_login_success", "line": 52, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:53.719046", "level": "INFO", "message": "Ventana principal creada para luis", "module": "main_window", "function": "__init__", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:46:53.787839", "level": "INFO", "message": "Ventana principal mostrada", "module": "main", "function": "on_login_success", "line": 56, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:47:43.355189", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 39, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:47:43.375166", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 27, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:47:43.511682", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 61, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:47:46.571765", "level": "INFO", "message": "Usuario autenticado: sdfsd", "module": "main", "function": "on_login_success", "line": 52, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:47:46.588124", "level": "INFO", "message": "Ventana principal creada para sdfsd", "module": "main_window", "function": "__init__", "line": 14, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:47:46.653639", "level": "INFO", "message": "Ventana principal mostrada", "module": "main", "function": "on_login_success", "line": 56, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:54:59.451703", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 39, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:54:59.471736", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 27, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:54:59.631853", "level": "CRITICAL", "message": "Error al iniciar aplicación: 'utf-8' codec can't decode byte 0xed in position 81: invalid continuation byte", "module": "main", "function": "main", "line": 66, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\main.py\", line 47, in main\n    login_window = LoginWindow()\n                   ^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\login_window.py\", line 12, in __init__\n    self.auth_controller = AuthController()\n                           ^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\controllers\\auth_controller.py\", line 6, in __init__\n    self.auth_service = AuthService()\n                        ^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\services\\auth_service.py\", line 6, in __init__\n    self.db = Database()\n              ^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\utils\\database.py\", line 11, in __init__\n    self.connection = self._create_connection()\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\utils\\database.py\", line 16, in _create_connection\n    return psycopg2.connect(\n           ^^^^^^^^^^^^^^^^^\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\site-packages\\psycopg2\\__init__.py\", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 81: invalid continuation byte"}
{"timestamp": "2025-07-28T21:58:49.361618", "level": "INFO", "message": "Iniciando aplicación Nova Desktop", "module": "main", "function": "main", "line": 37, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:58:49.391599", "level": "WARNING", "message": "No se pudo configurar HiDPI: type object 'ApplicationAttribute' has no attribute 'AA_EnableHighDpiScaling'", "module": "main", "function": "create_application", "line": 25, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:58:49.531711", "level": "ERROR", "message": "Error inesperado al conectar a PostgreSQL: 'utf-8' codec can't decode byte 0xed in position 81: invalid continuation byte", "module": "database", "function": "_create_connection", "line": 31, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:58:49.621436", "level": "INFO", "message": "Interfaz de login mostrada", "module": "main", "function": "main", "line": 68, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:58:58.376750", "level": "INFO", "message": "Intento de login para usuario: dssdf", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:58:58.376750", "level": "ERROR", "message": "No hay conexión a la base de datos", "module": "auth_service", "function": "validate_credentials", "line": 12, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:58:58.376750", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:59:12.188171", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:59:12.188171", "level": "ERROR", "message": "No hay conexión a la base de datos", "module": "auth_service", "function": "validate_credentials", "line": 12, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:59:12.197909", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:59:25.655978", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:59:25.655978", "level": "ERROR", "message": "No hay conexión a la base de datos", "module": "auth_service", "function": "validate_credentials", "line": 12, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:59:25.655978", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:59:52.235097", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:59:52.235097", "level": "ERROR", "message": "No hay conexión a la base de datos", "module": "auth_service", "function": "validate_credentials", "line": 12, "thread": "MainThread"}
{"timestamp": "2025-07-28T21:59:52.235097", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-28T22:00:01.919842", "level": "INFO", "message": "Intento de login para usuario: luis", "module": "auth_controller", "function": "authenticate", "line": 11, "thread": "MainThread"}
{"timestamp": "2025-07-28T22:00:01.919842", "level": "ERROR", "message": "No hay conexión a la base de datos", "module": "auth_service", "function": "validate_credentials", "line": 12, "thread": "MainThread"}
{"timestamp": "2025-07-28T22:00:01.919842", "level": "WARNING", "message": "Intento de login fallido", "module": "main", "function": "on_login_failed", "line": 57, "thread": "MainThread"}
{"timestamp": "2025-07-28T22:17:48.710683", "level": "CRITICAL", "message": "Excepción no capturada", "module": "main", "function": "handle_exception", "line": 15, "thread": "MainThread", "exception": "Traceback (most recent call last):\n  File \"E:\\DOCTORADO\\TOPICAVANZADO\\nova-desktop-system\\app\\views\\login_window.py\", line 50, in authenticate\n    QMessageBox.warning(self, \"Error\", \"Credenciales incorrectas\")\n  File \"E:\\MODELO MACHINE LEARNING TOTAL\\EXE\\envs\\nova-desktop\\Lib\\enum.py\", line 720, in __call__\n    def __call__(cls, value, names=_not_given, *values, module=None, qualname=None, type=None, start=1, boundary=None):\n    \nKeyboardInterrupt"}
